-- VAN ENTERTAINMENT: add VAN Universe, Leadership, and VAN Voice to navigation.
-- Safe to run more than once.

create table if not exists public.navigation_items (
    id bigint generated by default as identity primary key,
    label text not null,
    href text not null,
    location text not null default 'header' check (location in ('header','footer')),
    display_order integer not null default 0,
    is_visible boolean not null default true,
    is_external boolean not null default false,
    created_at timestamptz not null default now()
);

create unique index if not exists navigation_items_unique_idx
on public.navigation_items(location, label, href);

alter table public.navigation_items enable row level security;
grant select on public.navigation_items to anon, authenticated;
grant insert, update, delete on public.navigation_items to authenticated;
grant usage, select on sequence public.navigation_items_id_seq to authenticated;

drop policy if exists "van_public_read_navigation" on public.navigation_items;
create policy "van_public_read_navigation"
on public.navigation_items
for select
to anon, authenticated
using (is_visible = true or public.is_van_admin());

drop policy if exists "van_admin_manage_navigation" on public.navigation_items;
create policy "van_admin_manage_navigation"
on public.navigation_items
for all
to authenticated
using (public.is_van_admin())
with check (public.is_van_admin());

with required_menu(label, href, location, display_order) as (
    values
      ('Home','index.html','header',0),
      ('About','about.html','header',10),
      ('VAN Universe','universe.html','header',20),
      ('Leadership','leadership.html','header',30),
      ('Artists','artists.html','header',40),
      ('Survival','survival.html','header',50),
      ('News','news.html','header',60),
      ('Audition','audition.html','header',70),
      ('VAN Voice','voice.html','header',80),
      ('Contact','contact.html','header',90),
      ('About','about.html','footer',10),
      ('VAN Universe','universe.html','footer',20),
      ('Leadership','leadership.html','footer',30),
      ('Artists','artists.html','footer',40),
      ('Survival','survival.html','footer',50),
      ('News','news.html','footer',60),
      ('Audition','audition.html','footer',70),
      ('VAN Voice','voice.html','footer',80)
)
insert into public.navigation_items(label, href, location, display_order, is_visible, is_external)
select label, href, location, display_order, true, false
from required_menu r
where not exists (
    select 1 from public.navigation_items n
    where n.location = r.location and n.href = r.href
);

with required_menu(label, href, location, display_order) as (
    values
      ('Home','index.html','header',0),
      ('About','about.html','header',10),
      ('VAN Universe','universe.html','header',20),
      ('Leadership','leadership.html','header',30),
      ('Artists','artists.html','header',40),
      ('Survival','survival.html','header',50),
      ('News','news.html','header',60),
      ('Audition','audition.html','header',70),
      ('VAN Voice','voice.html','header',80),
      ('Contact','contact.html','header',90),
      ('About','about.html','footer',10),
      ('VAN Universe','universe.html','footer',20),
      ('Leadership','leadership.html','footer',30),
      ('Artists','artists.html','footer',40),
      ('Survival','survival.html','footer',50),
      ('News','news.html','footer',60),
      ('Audition','audition.html','footer',70),
      ('VAN Voice','voice.html','footer',80)
)
update public.navigation_items n
set label = r.label,
    display_order = r.display_order,
    is_visible = true,
    is_external = false
from required_menu r
where n.location = r.location and n.href = r.href;

create table if not exists public.custom_pages (
    id bigint generated by default as identity primary key,
    title text not null,
    slug text not null unique,
    eyebrow text,
    summary text,
    body_html text not null default '',
    cover_image text,
    cover_image_path text,
    is_published boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.custom_pages enable row level security;
grant select on public.custom_pages to anon, authenticated;
grant insert, update, delete on public.custom_pages to authenticated;
grant usage, select on sequence public.custom_pages_id_seq to authenticated;

drop policy if exists "van_public_read_custom_pages" on public.custom_pages;
create policy "van_public_read_custom_pages"
on public.custom_pages
for select
to anon, authenticated
using (is_published = true or public.is_van_admin());

drop policy if exists "van_admin_manage_custom_pages" on public.custom_pages;
create policy "van_admin_manage_custom_pages"
on public.custom_pages
for all
to authenticated
using (public.is_van_admin())
with check (public.is_van_admin());

insert into public.custom_pages(title, slug, eyebrow, summary, body_html, is_published)
values (
    'VAN UNIVERSE',
    'van-universe',
    'CONNECTED STORIES',
    'Explore the stories, eras, projects, and creative worlds connected across VAN ENTERTAINMENT.',
    '<h2>Welcome to VAN Universe</h2><p>VAN Universe is the home of every story, era, project, and connection within VAN ENTERTAINMENT.</p><h2>Artist Universes</h2><p>Add each artist or group storyline, timeline, concept era, symbols, and important connections here through Dashboard → Custom Pages.</p><h2>Project Archive</h2><p>Connect survival shows, pre-debut projects, collaborations, and future releases into one evolving universe.</p>',
    true
)
on conflict (slug) do nothing;

create table if not exists public.leadership_profiles (
    id bigint generated by default as identity primary key,
    name text not null,
    role text not null,
    division text,
    bio text,
    quote text,
    started_at date,
    projects text,
    email text,
    instagram_url text,
    profile_image text,
    profile_image_path text,
    status text not null default 'Active',
    display_order integer not null default 0,
    is_visible boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.leadership_profiles enable row level security;
grant select on public.leadership_profiles to anon, authenticated;
grant insert, update, delete on public.leadership_profiles to authenticated;
grant usage, select on sequence public.leadership_profiles_id_seq to authenticated;

drop policy if exists "van_public_read_leadership" on public.leadership_profiles;
create policy "van_public_read_leadership"
on public.leadership_profiles
for select
to anon, authenticated
using (is_visible = true or public.is_van_admin());

drop policy if exists "van_admin_manage_leadership" on public.leadership_profiles;
create policy "van_admin_manage_leadership"
on public.leadership_profiles
for all
to authenticated
using (public.is_van_admin())
with check (public.is_van_admin());


create table if not exists public.site_content (
    content_key text primary key,
    page_name text not null,
    label text not null,
    content_value text not null default '',
    field_type text not null default 'text' check (field_type in ('text','textarea','url','html')),
    display_order integer not null default 0,
    is_public boolean not null default true,
    updated_at timestamptz not null default now()
);

alter table public.site_content enable row level security;
grant select on public.site_content to anon, authenticated;
grant insert, update, delete on public.site_content to authenticated;

drop policy if exists "van_public_read_site_content" on public.site_content;
create policy "van_public_read_site_content"
on public.site_content
for select
to anon, authenticated
using (is_public = true or public.is_van_admin());

drop policy if exists "van_admin_manage_site_content" on public.site_content;
create policy "van_admin_manage_site_content"
on public.site_content
for all
to authenticated
using (public.is_van_admin())
with check (public.is_van_admin());

insert into public.site_content(content_key, page_name, label, content_value, field_type, display_order, is_public)
values
('home.hub.title','Homepage','Explore VAN title','MORE FROM VAN','text',200,true),
('home.hub.description','Homepage','Explore VAN description','Discover the stories, leadership, and community behind VAN ENTERTAINMENT.','textarea',210,true),
('home.universe.title','Homepage','VAN Universe card title','VAN UNIVERSE','text',220,true),
('home.universe.description','Homepage','VAN Universe card description','Explore the connected stories, eras, projects, and lore of VAN artists.','textarea',230,true),
('home.leadership.title','Homepage','Leadership card title','VAN LEADERSHIP','text',240,true),
('home.leadership.description','Homepage','Leadership card description','Meet the Founder, Co-Founder, CEOs, and executive team guiding VAN.','textarea',250,true),
('home.voice.title','Homepage','VAN Voice card title','VAN VOICE','text',260,true),
('home.voice.description','Homepage','VAN Voice card description','Join the community chat or send a private concern directly to VAN.','textarea',270,true)
on conflict (content_key) do nothing;

notify pgrst, 'reload schema';
