-- ============================================================
-- VAN ENTERTAINMENT CMS — SUPABASE SETUP
-- Run this entire file in Supabase > SQL Editor.
--
-- IMPORTANT:
-- Replace YOUR_OWNER_USER_UUID in the INSERT near the bottom
-- with the UUID shown in Supabase > Authentication > Users.
-- ============================================================

create table if not exists public.admin_users (
    user_id uuid primary key references auth.users(id) on delete cascade,
    created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

create or replace function public.is_van_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.admin_users
        where user_id = auth.uid()
    );
$$;

revoke all on function public.is_van_admin() from public;
grant execute on function public.is_van_admin() to anon, authenticated;

-- Existing artists table is preserved and upgraded.
create table if not exists public.artists (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text not null,
    artist_type text not null,
    debut_date date,
    description text,
    profile_image text,
    profile_image_path text,
    is_featured boolean not null default false,
    created_at timestamptz not null default now()
);

alter table public.artists add column if not exists name text;
alter table public.artists add column if not exists slug text;
alter table public.artists add column if not exists artist_type text;
alter table public.artists add column if not exists debut_date date;
alter table public.artists add column if not exists description text;
alter table public.artists add column if not exists profile_image text;
alter table public.artists add column if not exists profile_image_path text;
alter table public.artists add column if not exists is_featured boolean not null default false;
alter table public.artists add column if not exists created_at timestamptz not null default now();

create unique index if not exists artists_slug_unique_idx on public.artists (slug);

create table if not exists public.members (
    id bigint generated by default as identity primary key,
    artist_id text not null,
    name text not null,
    position text,
    birth_date date,
    description text,
    display_order integer not null default 0,
    profile_image text,
    profile_image_path text,
    created_at timestamptz not null default now()
);

create index if not exists members_artist_id_idx on public.members (artist_id);

create table if not exists public.albums (
    id bigint generated by default as identity primary key,
    artist_id text not null,
    title text not null,
    album_type text,
    release_date date,
    spotify_url text,
    cover_image text,
    cover_image_path text,
    created_at timestamptz not null default now()
);

create index if not exists albums_artist_id_idx on public.albums (artist_id);

create table if not exists public.music_videos (
    id bigint generated by default as identity primary key,
    artist_id text not null,
    title text not null,
    release_date date,
    youtube_url text not null,
    thumbnail_image text,
    thumbnail_image_path text,
    created_at timestamptz not null default now()
);

create index if not exists music_videos_artist_id_idx on public.music_videos (artist_id);

create table if not exists public.news (
    id bigint generated by default as identity primary key,
    title text not null,
    slug text not null,
    summary text,
    content text not null,
    publish_date date,
    cover_image text,
    cover_image_path text,
    is_published boolean not null default false,
    created_at timestamptz not null default now()
);

create unique index if not exists news_slug_unique_idx on public.news (slug);

alter table public.artists enable row level security;
alter table public.members enable row level security;
alter table public.albums enable row level security;
alter table public.music_videos enable row level security;
alter table public.news enable row level security;

-- Remove only policies created by this setup file, so unrelated existing
-- policies are not touched.
drop policy if exists "van_public_read_artists" on public.artists;
drop policy if exists "van_admin_insert_artists" on public.artists;
drop policy if exists "van_admin_update_artists" on public.artists;
drop policy if exists "van_admin_delete_artists" on public.artists;

create policy "van_public_read_artists" on public.artists for select using (true);
create policy "van_admin_insert_artists" on public.artists for insert to authenticated with check (public.is_van_admin());
create policy "van_admin_update_artists" on public.artists for update to authenticated using (public.is_van_admin()) with check (public.is_van_admin());
create policy "van_admin_delete_artists" on public.artists for delete to authenticated using (public.is_van_admin());

-- Related public tables.
do $$
declare
    table_name text;
begin
    foreach table_name in array array['members','albums','music_videos'] loop
        execute format('drop policy if exists %I on public.%I', 'van_public_read_' || table_name, table_name);
        execute format('drop policy if exists %I on public.%I', 'van_admin_insert_' || table_name, table_name);
        execute format('drop policy if exists %I on public.%I', 'van_admin_update_' || table_name, table_name);
        execute format('drop policy if exists %I on public.%I', 'van_admin_delete_' || table_name, table_name);

        execute format('create policy %I on public.%I for select using (true)', 'van_public_read_' || table_name, table_name);
        execute format('create policy %I on public.%I for insert to authenticated with check (public.is_van_admin())', 'van_admin_insert_' || table_name, table_name);
        execute format('create policy %I on public.%I for update to authenticated using (public.is_van_admin()) with check (public.is_van_admin())', 'van_admin_update_' || table_name, table_name);
        execute format('create policy %I on public.%I for delete to authenticated using (public.is_van_admin())', 'van_admin_delete_' || table_name, table_name);
    end loop;
end $$;

drop policy if exists "van_public_read_news" on public.news;
drop policy if exists "van_admin_read_news" on public.news;
drop policy if exists "van_admin_insert_news" on public.news;
drop policy if exists "van_admin_update_news" on public.news;
drop policy if exists "van_admin_delete_news" on public.news;

create policy "van_public_read_news" on public.news for select to anon using (is_published = true);
create policy "van_admin_read_news" on public.news for select to authenticated using (public.is_van_admin());
create policy "van_admin_insert_news" on public.news for insert to authenticated with check (public.is_van_admin());
create policy "van_admin_update_news" on public.news for update to authenticated using (public.is_van_admin()) with check (public.is_van_admin());
create policy "van_admin_delete_news" on public.news for delete to authenticated using (public.is_van_admin());

grant select on public.artists, public.members, public.albums, public.music_videos, public.news to anon, authenticated;
grant insert, update, delete on public.artists, public.members, public.albums, public.music_videos, public.news to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Public media bucket used by the CMS.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'artist-images',
    'artist-images',
    true,
    5242880,
    array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "van_public_read_media" on storage.objects;
drop policy if exists "van_admin_insert_media" on storage.objects;
drop policy if exists "van_admin_update_media" on storage.objects;
drop policy if exists "van_admin_delete_media" on storage.objects;

create policy "van_public_read_media" on storage.objects for select using (bucket_id = 'artist-images');
create policy "van_admin_insert_media" on storage.objects for insert to authenticated with check (bucket_id = 'artist-images' and public.is_van_admin());
create policy "van_admin_update_media" on storage.objects for update to authenticated using (bucket_id = 'artist-images' and public.is_van_admin()) with check (bucket_id = 'artist-images' and public.is_van_admin());
create policy "van_admin_delete_media" on storage.objects for delete to authenticated using (bucket_id = 'artist-images' and public.is_van_admin());

-- ------------------------------------------------------------
-- OWNER ACCESS: replace the UUID below, then remove the leading --
-- Example:
-- insert into public.admin_users (user_id)
-- values ('12345678-1234-1234-1234-123456789abc')
-- on conflict (user_id) do nothing;
-- ------------------------------------------------------------
 insert into public.admin_users (user_id)
 values ('c28ba16b-2b95-41a4-92e2-bccfd5f3bfeb')
 on conflict (user_id) do nothing;
