-- =============================================================
-- VAN VOICE CHAT MIGRATION
-- Run this once in Supabase > SQL Editor.
-- Keeps Private Report tickets, but makes Public/Anonymous posts
-- appear immediately as a community chat.
-- =============================================================

create extension if not exists pgcrypto;

-- Existing ticket table upgrades
alter table public.feedback_tickets
    add column if not exists reply_to_id uuid
        references public.feedback_tickets(id)
        on delete set null,
    add column if not exists client_id text,
    add column if not exists report_count integer not null default 0;

-- Public messages are approved immediately by default.
alter table public.feedback_tickets
    alter column moderation_status set default 'Approved';

-- Publish old public/anonymous messages that are still pending.
update public.feedback_tickets
set moderation_status = 'Approved',
    updated_at = now()
where visibility in ('Public', 'Anonymous')
  and moderation_status = 'Pending';

create index if not exists feedback_tickets_created_at_idx
    on public.feedback_tickets(created_at desc);

create index if not exists feedback_tickets_reply_to_idx
    on public.feedback_tickets(reply_to_id);

create index if not exists feedback_tickets_client_rate_idx
    on public.feedback_tickets(client_id, created_at desc)
    where client_id is not null;

-- Reports submitted from the public chat.
create table if not exists public.voice_message_reports (
    id bigint generated by default as identity primary key,
    message_id uuid not null
        references public.feedback_tickets(id)
        on delete cascade,
    client_id text not null,
    reason text,
    created_at timestamptz not null default now(),
    unique (message_id, client_id)
);

alter table public.voice_message_reports enable row level security;
revoke all on public.voice_message_reports from anon, authenticated;

-- -------------------------------------------------------------
-- Submit public chat message OR private report.
-- Public/Anonymous: instantly Approved and visible.
-- Private: remains private and receives ticket code + PIN.
-- -------------------------------------------------------------
create or replace function public.submit_van_feedback(payload jsonb)
returns table (
    id uuid,
    ticket_code text,
    access_pin text,
    visibility text
)
language plpgsql
security definer
set search_path = public
as $$
declare
    inserted public.feedback_tickets;
    requested_visibility text;
    requested_reply uuid;
    requested_client_id text;
    recent_count integer;
begin
    requested_visibility := initcap(lower(coalesce(nullif(trim(payload->>'visibility'), ''), 'Public')));

    if requested_visibility not in ('Public', 'Private', 'Anonymous') then
        raise exception 'Invalid visibility option.';
    end if;

    if coalesce(trim(payload->>'target_type'), '') = ''
       or coalesce(trim(payload->>'category'), '') = ''
       or length(coalesce(trim(payload->>'message'), '')) < 2 then
        raise exception 'Please complete the required VAN Voice fields.';
    end if;

    requested_client_id := nullif(trim(payload->>'client_id'), '');

    -- Basic anti-spam: max 5 submissions per browser ID in 10 minutes.
    if requested_client_id is not null then
        select count(*)
        into recent_count
        from public.feedback_tickets
        where client_id = requested_client_id
          and created_at > now() - interval '10 minutes';

        if recent_count >= 5 then
            raise exception 'Too many messages. Please try again in a few minutes.';
        end if;
    end if;

    if nullif(trim(payload->>'reply_to_id'), '') is not null then
        begin
            requested_reply := (payload->>'reply_to_id')::uuid;
        exception when invalid_text_representation then
            requested_reply := null;
        end;

        -- Replies can only point to a visible public message.
        if requested_reply is not null and not exists (
            select 1
            from public.feedback_tickets parent
            where parent.id = requested_reply
              and parent.visibility in ('Public', 'Anonymous')
              and parent.moderation_status = 'Approved'
        ) then
            requested_reply := null;
        end if;
    end if;

    insert into public.feedback_tickets (
        sender_name,
        sender_email,
        sender_whatsapp,
        target_type,
        target_name,
        category,
        visibility,
        title,
        message,
        priority,
        status,
        moderation_status,
        reply_to_id,
        client_id
    )
    values (
        case
            when requested_visibility = 'Anonymous' then null
            else nullif(trim(payload->>'sender_name'), '')
        end,
        nullif(lower(trim(payload->>'sender_email')), ''),
        nullif(trim(payload->>'sender_whatsapp'), ''),
        trim(payload->>'target_type'),
        nullif(trim(payload->>'target_name'), ''),
        trim(payload->>'category'),
        requested_visibility,
        coalesce(
            nullif(trim(payload->>'title'), ''),
            case
                when requested_visibility = 'Private' then 'Private VAN Voice Report'
                else 'Community Message'
            end
        ),
        trim(payload->>'message'),
        case
            when requested_visibility = 'Private'
                then coalesce(nullif(trim(payload->>'priority'), ''), 'Normal')
            else 'Normal'
        end,
        'New',
        case
            when requested_visibility = 'Private' then 'Pending'
            else 'Approved'
        end,
        case
            when requested_visibility = 'Private' then null
            else requested_reply
        end,
        requested_client_id
    )
    returning * into inserted;

    return query
    select
        inserted.id,
        inserted.ticket_code,
        inserted.access_pin,
        inserted.visibility;
end;
$$;

revoke all on function public.submit_van_feedback(jsonb) from public;
grant execute on function public.submit_van_feedback(jsonb) to anon, authenticated;

-- -------------------------------------------------------------
-- Public report button.
-- One report per browser ID. Five unique reports auto-hide a post.
-- Admin can restore it by setting moderation_status = 'Approved'.
-- -------------------------------------------------------------
create or replace function public.report_van_feedback(
    p_message_id uuid,
    p_reason text,
    p_client_id text
)
returns table (
    report_count integer,
    hidden boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_count integer;
    v_hidden boolean;
begin
    if coalesce(trim(p_client_id), '') = '' then
        raise exception 'Reporter identity is missing.';
    end if;

    if not exists (
        select 1
        from public.feedback_tickets f
        where f.id = p_message_id
          and f.visibility in ('Public', 'Anonymous')
          and f.moderation_status = 'Approved'
    ) then
        raise exception 'This message is no longer available.';
    end if;

    insert into public.voice_message_reports(message_id, client_id, reason)
    values (
        p_message_id,
        trim(p_client_id),
        nullif(left(trim(coalesce(p_reason, '')), 500), '')
    )
    on conflict (message_id, client_id) do nothing;

    select count(*)
    into v_count
    from public.voice_message_reports
    where message_id = p_message_id;

    v_hidden := v_count >= 5;

    update public.feedback_tickets
    set report_count = v_count,
        moderation_status = case when v_hidden then 'Hidden' else moderation_status end,
        updated_at = now()
    where id = p_message_id;

    return query select v_count, v_hidden;
end;
$$;

revoke all on function public.report_van_feedback(uuid, text, text) from public;
grant execute on function public.report_van_feedback(uuid, text, text) to anon, authenticated;

-- -------------------------------------------------------------
-- Safe public view. It deliberately excludes email, WhatsApp,
-- PIN, client_id, and internal admin notes.
-- -------------------------------------------------------------
drop view if exists public.public_feedback_posts;

create view public.public_feedback_posts as
select
    f.id,
    f.ticket_code,
    f.target_type,
    f.target_name,
    f.category,
    f.visibility,
    f.title,
    f.message,
    f.status,
    f.official_response,
    f.reply_to_id,
    f.report_count,
    f.created_at,
    f.updated_at,
    case
        when f.visibility = 'Anonymous' then 'Anonymous'
        else coalesce(nullif(trim(f.sender_name), ''), 'VAN Community Member')
    end as display_name,
    case
        when parent.id is null then null
        when parent.visibility = 'Anonymous' then 'Anonymous'
        else coalesce(nullif(trim(parent.sender_name), ''), 'VAN Community Member')
    end as reply_to_name,
    case
        when parent.id is null then null
        else left(parent.message, 180)
    end as reply_to_message
from public.feedback_tickets f
left join public.feedback_tickets parent
    on parent.id = f.reply_to_id
   and parent.visibility in ('Public', 'Anonymous')
   and parent.moderation_status = 'Approved'
where f.visibility in ('Public', 'Anonymous')
  and f.moderation_status = 'Approved';

grant select on public.public_feedback_posts to anon, authenticated;

-- Keep private ticket tracking available.
create or replace function public.track_van_feedback(
    p_ticket_code text,
    p_access_pin text
)
returns table (
    ticket_code text,
    title text,
    target_type text,
    target_name text,
    category text,
    visibility text,
    status text,
    moderation_status text,
    message text,
    official_response text,
    created_at timestamptz,
    updated_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
    select
        f.ticket_code,
        f.title,
        f.target_type,
        f.target_name,
        f.category,
        f.visibility,
        f.status,
        f.moderation_status,
        f.message,
        f.official_response,
        f.created_at,
        f.updated_at
    from public.feedback_tickets f
    where upper(f.ticket_code) = upper(trim(p_ticket_code))
      and f.access_pin = trim(p_access_pin)
    limit 1;
$$;

revoke all on function public.track_van_feedback(text, text) from public;
grant execute on function public.track_van_feedback(text, text) to anon, authenticated;

notify pgrst, 'reload schema';
